### ISSUE TITLE
[ISTHMUS] Null value support in filter

### ISSUE THREAD

**Issue by Deegue** [substrait-io/substrait-java#61] opened 2022-06-24 07:47 UTC
Hi, it seems we don't support null data in filter currently, e.g
table : 
`CREATE TABLE table_test(col_a BIGINT)`
query : 
`SELECT col_a FROM table_test WHERE col_a IS NOT NULL` or
`SELECT col_a FROM table_test WHERE col_a != NULL`

Any help will be appreciated!

**Comment by jacques-n** [comment] 2022-06-26 21:59
I'm guessing that we haven't yet added a Calcite to Substrait function mapping. Would you be open to propose a patch to add that in? We already have the function defined [here](https://github.com/substrait-io/substrait/blob/9b0e21f5f3d8334a6a291ca06fcc2bd04d6007be/extensions/functions_comparison.yaml#L61).

**Comment by Deegue** [comment] 2022-06-28 11:18
> I'm guessing that we haven't yet added a Calcite to Substrait function mapping. Would you be open to propose a patch to add that in? We already have the function defined [here](https://github.com/substrait-io/substrait/blob/9b0e21f5f3d8334a6a291ca06fcc2bd04d6007be/extensions/functions_comparison.yaml#L61).

Thanks, I submit a PR and could you take a look at it?

**Comment by JamesRTaylor** [comment] 2022-07-18 15:52
Duplicate of https://github.com/substrait-io/substrait-java/issues/66

**Closed by JamesRTaylor** 2022-07-18 15:52 UTC
